FROM quay.io/jupyter/minimal-notebook:latest

WORKDIR /opt/pbp

RUN pip install mbari-pbp==0.3.0b19

USER root
RUN apt-get update && apt-get install -y libsox-fmt-all libsox-dev
RUN chown -R jovyan /opt/pbp
USER jovyan

ENV PYTHONPATH /opt/pbp:/opt/pbp/pbp
EXPOSE 8899

CMD ["/opt/conda/bin/jupyter", "notebook", "--notebook-dir=/opt/pbp", "--ip='*'","--port=8899","--no-browser", "--allow-root"]
