DEFAULT_LAT_LON_FOR_SOLPOS = (36.7128, -122.186)

DEFAULT_TITLE = (
    "MBARI MARS Cabled Observatory   Monterey Bay, California, USA"
    f"   {DEFAULT_LAT_LON_FOR_SOLPOS[0]} \xb0N, {DEFAULT_LAT_LON_FOR_SOLPOS[1]} \xb0W"
)

DEFAULT_YLIM = (10, 100000)

DEFAULT_DPI = 200
