name: Installation Test

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install hdf5 libsndfile
        echo "HDF5_DIR=$(brew --prefix hdf5)" >> $GITHUB_ENV

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libhdf5-dev libnetcdf-dev libsndfile1

    - name: Install system dependencies (Windows)
      if: runner.os == 'Windows' && matrix.python-version == '3.11'
      run: |
        echo "Relying on pre-compiled wheels for Windows dependencies"

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install mbari-pbp
      run: |
        pip install mbari-pbp

    - name: Verify installation
      run: |
        python -c "import pbp; print(f'Successfully imported pbp version: {pbp.get_pbp_version()}')"

    - name: Test basic functionality
      run: |
        python -c "
        import pbp
        import soundfile
        import pyarrow
        print('Installation and key dependencies verified!')
        "